const settingsFR = {
  noDataMessage: '',

  pager: {
    display: true,
    perPage: 15,
  },

  actions: {
    add: false,
    edit: false,
    delete: false,
  },
  columns: {
    reference: {
      title: 'Ref. Produit',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    name: {
      title: 'Nom du Produit',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    gencod: {
      title: 'Gencod',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    customsReference: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    originCountry: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    description: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    currency: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    fobGrossPrice: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    fobNetPrice: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    ddpGrossPrice: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    ddpNetPrice: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    exWorksGrossPrice: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    exWorksNetPrice: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    paymentTerms: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    dateOfValidity: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    departurePlace: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    isExclusivityJc: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    isSpecialBoxJc: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    availabilityProduct: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    minimumQuantity: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    outerColisage: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    innerColisage: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    itemsQuantity20: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    itemsQuantity40: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    outCartonCbm: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    colisageGrossWeight: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    colisageNetWeight: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    outerCartonDimension: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    productDimension: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    boxDimension: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    colors: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    models: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    packagingLanguage: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    manualLanguage: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    productLanguage: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    age: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    productNetWeight: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    productGrossWeight: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    isAccuIncluded: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    accusType: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    isBatteriesIncluded: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    batteryType: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    isBatteries2Included: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    batteryType2: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    isBatteries3Included: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    batteryType3: {
      title: 'Référence',
      type: 'string',
      sort: true,
      editable: false,
      // width: '10px',
    },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },
    // batteryType: {
    //   title: 'Référence',
    //   type: 'string',
    //   sort: true,
    //   editable: false,
    //   // width: '10px',
    // },



    title: {
      title: 'Nom du Produit',
      type: 'string',
      editable: false,
      valuePrepareFunction: (value) => {
        return (value.length > 10 ? value.substring(0, 10) + '...' : value);
      },
    },
    details: {
      title: 'Description',
      type: 'string',
      editable: false,
      valuePrepareFunction: (value) => {
        return (value.length > 10 ? value.substring(0, 10) + '...' : value);
      },
    },
    price: {
      title: 'Prix',
      type: 'string',
      editable: false,
      sort: true,
    },
    pintelSheetId: {
      title: 'Fiche Pintel',
      type: 'string',
      sort: true,
      editable: false,
      width: '10px',
    },
    originId: {
      title: 'Origine',
      type: 'string',
      sort: true,
      editable: false,
      width: '10px',
    },
    supplierId: {
      title: 'ID Fournisseur',
      type: 'string',
      sort: true,
      editable: false,
      width: '10px',
    },
  },
};
